app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # index.html
    path('', views.homepage, name="homepage"),
    # public survey
    path('survey/', views.picksurvey, name="test-picksurvey"),
    path('survey/<testid>/start/<int:userid>', views.teststart, name="test-start"),
    path('survey/<testid>/<userid>/<int:caseid>', views.testcase, name="test-case"),
    path('survey/<testid>/<userid>/end/', views.testend, name="test-end"),
    # private survey
    path('survey/<testid>/settings/', views.testsettings, name="test-settings"),
    path('survey/<testid>/results/', views.testresults, name="test-results"),
    path('survey/<testid>/delete/', views.testdelete, name="test-delete"),    
    path('create/', views.testcreate, name="test-create"),
    path('reports/<int:reportid>/', views.testfinalresults, name="test-final-results"),
    # general settings for surveys
    path('create/settings/', views.testcreatesettings, name="test-createsettings"),
    path('create/settings/variable/<variableid>/delete', views.settingsvariabledelete, name="test-settingsvariabledelete"),
    path('create/settings/template/<templateid>', views.testtemplateedit, name="test-templateedit"),
    path('create/preview/template/<templateid>', views.templatepreview, name="preview-template"),
    path('create/settings/template/<templateid>/delete', views.testtemplatedelete, name="test-templatedelete"),
    path('create/settings/form/<formid>', views.formedit, name="test-formedit"),
    path('create/settings/form/<formid>/delete', views.formdelete, name="test-formdelete"),
]

brain/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views

#for media in dev mode
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # setup section
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
    path('accounts/profile/', user_views.profile_redirect, name="profile_redirect"),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True), name="login"), 
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name="logout"),
    # other sections
    path('imprint/', user_views.imprint, name="imprint"),
    # study section
    path('', include(('app.urls', 'app'),namespace='app')),
] 

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'user.views.error_404'
handler500 = 'user.views.error_500'

app/templates/app/error.html
{% extends "app/header.html" %}
{% load static %}
{% block content %}
            <section class="hero pad">
                <div class="boxCenter">
                    <h1>This url does not exist.</h1>
                    <div>
                        <img src="{% static 'app/404.svg' %}" height="160" width="160" alt="404 error"/>
                    </div>
                    <a href="{% url 'app:homepage' %}">Go back home</a>
                </div>
            </section>
{% endblock %}

app/templates/app/form-edit.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<style>
.settings-category {
    position: relative;
    z-index: 8;
    margin-bottom: 2rem;
    top: 8rem;
}
.list-item-settings {
    color: black;
    margin: 0.5rem 0 0.5rem 0;
}

.padGridWrapper {
    padding: 0 2rem 2rem 2rem;
    margin: 0 0 4rem 0;
}
</style>
{% endblock %}
{% block content %}
            <section class="gridWrapper padGridWrapper">
                <div class="boxLeft pad">
                    <div class="boxHeader">
                        <h1>Form Settings</h1>
                        <span type="button" id="delete" class="collapsible"><a href="{% url 'app:test-formdelete' formid=formid %}" onclick="return confirm('Are you sure you want to delete this form?');"><img src="{% static 'app/close.svg' %}" height="24" width="24"></a></span>
                    </div>
                </div>
                <div class="boxRight pad">
                    <div class="boxHeader">
                        <h1>Settings</h1>
                    </div>
                    <!-- section setting -->
                    <div class="boxHeader">
                        <div class="boxForm">
                            <form id="formEdit" method="post">
                                {% csrf_token %}
                                {{ formEdit }}
                                <button type="submit" name="formEdit">EDIT FORM</button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            {% if messages %}
            <div id="errorBar" class="error_message">
                {% for message in messages %}
                <span>{{ message }}</span> 
                {% endfor %}
                <button class="error_button" onclick="errorBar()"> X </button>
            </div>
            {% endif %}
{% endblock %}

{% block jsfile %}
{% endblock %}

app/templates/app/header-share.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;700;900&display=swap" rel="stylesheet"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.css"rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body>
    <header class="pad" id="header">
        <a href="{% url 'app:homepage' %}" class="logo"><img src="{% static 'app/mty_logo.png' %}" alt="BI home"
                    class="logo-header" /></a>
        <input type="checkbox" class="nav-toggle" id="nav-toggle" tabindex="-1">
        <nav id="nav" aria-label="Main Navigation">
            <ul>
            </ul>
        </nav>
        <label for="nav-toggle" class="nav-toggle-label" id="nav-menu-button" aria-controls="nav-toggle"
            aria-label="Open navigation menu">
            <span></span><span class="menu-toggle">Menu toggle</span>
        </label>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer class="pad6">
        <div class="menu-footer">
            <div class="menu-footer-item">
                <h3>Contact us</h3>
                <ul>
                    <li><a href="tel:+49-176-59864734">+49 176 59864734</a></li>
                    <li><a href="mailto:info@mtymedia.de">e-mail</a></li>
                </ul>
            </div>
            <div class="menu-footer-item">
                <h3>Legal</h3>
                <ul>
                    <li><a href="https://mtymedia.de/privacy">Privacy & Policy</a></li>
                    <li><a href="https://mtymedia.de/impressum">Imprint</a></li>
                </ul>
            </div>
        </div>
        <div class="copyright">
            &copy; Copyright 2022, Mtymedia.
        </div>
    </footer>
    <script src="{% static 'app/main.js' %}"></script>
    {% block jsfile %}{% endblock %}
</body>

</html>

app/templates/app/index.html
{% extends "app/header.html" %}
{% load static %}
{% block content %}
            <section class="hero pad">
                <div class="boxCenter surveyBox">
                    <h1 class="surveyTitle">Copy of Survey for Master's Thesis. (This is a TEST ONLY THE ENGLISH - M is working)</h1>
                    <h2 class="surveySubtitle"><img src="{% static 'app/logobtu.png' %}" height="20" width="120" alt="german survey"/></h2>
                    <div class="surveyChoice">
                        <a class="surveyText" href="http://127.0.0.1:8000/survey/8/start/0">
                            <img src="{% static 'app/germany.png' %}" height="64" width="64" alt="german survey"/>
                            Fragebogen starten
                        </a>
                    </div>
                    <div class="surveyChoice">
                        <a class="surveyText" href="http://127.0.0.1:8000/survey/8/start/0">
                            <img src="{% static 'app/italy.png' %}" height="64" width="64" alt="italian survey"/>
                            Inizia il questionario
                        </a>
                    </div>
                    <div class="surveyChoice">
                        <a class="surveyText" href="http://127.0.0.1:8000/survey/8/start/0">
                            <img src="{% static 'app/english.png' %}" height="64" width="64" alt="english survey"/>
                            Start the survey
                        </a>
                    </div>
                </div>
                <!--
                <div class="boxLeftHome">
                    <h1 class="outline title">Survey</h1>
                    <h2 class="outline subtitle">App</h2>
                </div>
                -->
            </section>
{% endblock %}

app/templates/app/main-settings.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<style>

</style>
{% endblock %}
{% block content %}
            <section class="gridWrapper padGridWrapper">
                <div class="boxLeft pad">
                    <div class="boxHeader">
                        <h1>Main Settings</h1>
                        <ul>
                            <li class="list-item-settings"><a href="#varAndSeg">Variables</a></li>
                            <li class="list-item-settings"><a href="#varTemplate">Templates</a></li>
                            <li class="list-item-settings"><a href="#varForm">Form</a></li>
                            <li class="list-item-settings"><a href="#counters">Counters</a></li>
                            <li class="list-item-settings"><a href="#reports">Reports</a></li>
                        </ul>
                    </div>
                </div>
                <div class="boxRight pad">
                    <div class="boxHeader">
                        <h1>Settings</h1>
                    </div>

                    <!-- section delete -->
                    <div id="varAndSeg" class="boxHeader settings-category">
                        <h1>Delete</h1>
                        <div class="boxForm">
                            <form id="deleteStuff" method="post">
                                {% csrf_token %}
                                <button type="submit" name="deleteStuff">DELETE ALL</button>
                            </form>
                        </div>
                    </div>


                    <!-- section setting -->
                    <div id="varAndSeg" class="boxHeader settings-category">
                        <h1>Variables & Segments</h1>
                        <div class="boxForm">
                            <form id="formNewVariablesCategory" method="post">
                                {% csrf_token %}
                                {{ formNewVariablesCategory }}
                                <button type="submit" name="addNewVariablesCategory">ADD VARIABLE</button>
                            </form>
                        </div>
                        <div class="cardContainer" style="overflow-x:auto;">
                            <table id="creators-table" data-name="product-table">
                                <tr id="tableHeader">
                                    <th scope="col">Action!</th>
                                    <th scope="col">ID</th>
                                    <th scope="col">Tag</th>
                                    <th scope="col">Max Seg</th>
                                    <th scope="col">Name</th>
                                </tr>
                                {% for vc in variables_category %}
                                <tr class="tbc">
                                    <td class="button-table"><a href="{% url 'app:test-settingsvariabledelete' variableid=vc.id %}">DELETE</a></td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{vc.id}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{vc.tag}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{vc.max_segments}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{vc.name}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                    </div>
                    </div>
                    <!-- section setting -->
                    <div id="varTemplate" class="boxHeader settings-category">
                        <h1>Templates</h1>
                        <div class="boxForm">
                            <form id="formNewVariableTemplates" method="post">
                                {% csrf_token %}
                                {{ formNewVariableTemplates }}
                                <button type="submit" name="addNewVariableTemplate">ADD TEMPLATE</button>
                            </form>
                        </div>
                        <div class="cardContainer" style="overflow-x:auto;">
                            <table id="creators-table" data-name="product-table">
                                <tr id="tableHeader">
                                    <th scope="col">Action!</th>
                                    <th scope="col">ID</th>
                                    <th scope="col">Var ID</th>
                                    <th scope="col">0 Template</th>
                                    <th scope="col">Name</th>
                                </tr>
                                {% for template in templates %}
                                <tr class="tbc">
                                    <td class="button-table"><a href="{% url 'app:test-templateedit' templateid=template.id %}">EDIT</a></td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{template.id}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{template.variable_id}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{template.zero_template}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{template.name}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                    </div>
                    </div>
                    <!-- section setting -->
                    <div id="varForm" class="boxHeader settings-category">
                        <h1>Forms</h1>
                        <div class="boxForm">
                            <form id="formSurvey" method="post">
                                {% csrf_token %}
                                {{ formSurvey }}
                                <button type="submit" name="formSurvey">ADD FORM</button>
                            </form>
                        </div>
                        <div class="cardContainer" style="overflow-x:auto;">
                            <table id="creators-table" data-name="product-table">
                                <tr id="tableHeader">
                                    <th scope="col">Action!</th>
                                    <th scope="col">language</th>
                                    <th scope="col">Is Start?</th>
                                    <th scope="col">tag</th>
                                    <th scope="col">name</th>
                                </tr>
                                {% for form in forms %}
                                <tr class="tbc">
                                    <td class="button-table"><a href="{% url 'app:test-formedit' formid=form.id %}">EDIT</a></td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{form.language}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{form.is_start}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{form.template_tag}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{form.name}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                    </div>
                    </div>
                    <!-- section setting -->
                    <div id="counters" class="boxHeader settings-category">
                        <h1>Counters</h1>
                        <div class="boxForm">
                            <form id="formCounterSurvey" method="post">
                                {% csrf_token %}
                                {{ formCounterSurvey }}
                                <button type="submit" name="addFormCounter">ADD VARIABLE</button>
                            </form>
                        </div>
                        <div class="cardContainer" style="overflow-x:auto;">
                            <table id="creators-table" data-name="product-table">
                                <tr id="tableHeader">
                                    <th scope="col">id</th>
                                    <th scope="col">unique_id</th>
                                    <th scope="col">CO</th>
                                    <th scope="col">TR</th>
                                    <th scope="col">SE</th>
                                    <th scope="col">CM</th>
                                    <th scope="col">Counter</th>
                                </tr>
                                {% for counter in counters %}
                                <tr class="tbc">
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{counter.id}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{counter.unique_id}}</td>
                                    <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{counter.co}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{counter.tr}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{counter.se}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{counter.cm}}</td>
                                    <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{counter.counter}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                    </div>
                    </div>
                    <!-- section setting -->
                    <div id="reports" class="boxHeader settings-category">
                        <div class="boxHeader">
                            <ul>
                                <li class="list-item-settings"><a href="{% url 'app:test-final-results' reportid=1 %}">Users</a></li>
                                <li class="list-item-settings"><a href="{% url 'app:test-final-results' reportid=2 %}">Sensitive</a></li>
                                <li class="list-item-settings"><a href="{% url 'app:test-final-results' reportid=3 %}">Context</a></li>
                                <li class="list-item-settings"><a href="{% url 'app:test-final-results' reportid=4 %}">Final Results</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>
            {% if messages %}
            <div id="errorBar" class="error_message">
                {% for message in messages %}
                <span>{{ message }}</span> 
                {% endfor %}
                <button class="error_button" onclick="errorBar()"> X </button>
            </div>
            {% endif %}
{% endblock %}

{% block jsfile %}
{% endblock %}

app/templates/app/survey-case.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{% autoescape off %}
{% for code in code_css %}
<style>
    {{code }}
</style>
{% endfor %}
{% endautoescape %}

<style>

</style>
{% endblock %}
{% block content %}
<section class="gridWrapper padGridWrapper">
    <div class="boxLeftSurvey pad">
      <div class="boxHeader">
        <h1>{{ info.caseid }} / {{survey_lenght}}</h1>
      </div>
      <div class="container">
        <div class="fake-browser">
          <div class="fake-browser-header">
            <div class="action-btns">
              <span></span>
              <span></span> 
              <span></span>
            </div>
            <div class="address-bar" id="domain">
              
            </div>
            <div class="setting-more">
            </div>
          </div>
          <section class="fake-window-body">
            {% autoescape off %}
            {% for code in code_html %}
            {{ code }}
            {% endfor %}
            {% endautoescape %}
            </section>
        </div>
      </div>
    </div>
    <div class="boxRightSurvey pad">
      <div class="boxHeader">
        <h1>{{title_question}}</h1>
    </div>
    {% if text_external %}
    <div class="boxInfoHome surveyCase">
        {{ text_external }}
    </div>
    {% endif %}
    <div class="formContainer" id="formDiv">
      <div class="boxForm sticky">

          <form method="post" action="{% url 'app:test-case' testid=info.testid userid=info.userid caseid=info.nextid %}">
              {% csrf_token %}
              {{ form }}
              <hr>
              <button id="formAnswer" type="submit" name="formAnswer">{{ text_button }}</button>
          </form>
      </div>
    </div>
    </div>
</section>
{% endblock %}

{% block jsfile %}
<script>
    {% autoescape off %}
    {% for code in code_js %}
    {{ code }}
    {% endfor %}
    {% endautoescape %}
</script>
<script>
var yes = document.getElementById("yes")
var no = document.getElementById("no")

function closeCookie() {
  var cookiesfullscreen = document.getElementById("stufffullscreen");
  cookiesfullscreen.style.display = "none";
}
</script>
{% endblock %}

app/templates/app/survey-end.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<style>

</style>
{% endblock %}
{% block content %}
            <section class="hero pad">
                <div class="boxCenter">
                        {% if redirect.last_survey %}
                        <h1>{{ redirect.survey_end_text }}</h1>
                        <img src="{% static 'app/thank-you.png' %}" height="64" width="64" alt="end survey"/>
                        {% else %}
                        <h2>{{ redirect.survey_end_text }}: <a href="{% url 'app:test-start' testid=redirect.redirect_to userid=redirect.userid %}" id="red-link">next</a></h2>
                        <div style="display:none">
                            <form action="{% url 'app:test-start' testid=redirect.redirect_to userid=redirect.userid %}" method="post" id="redirect">
                                {% csrf_token %}
                                <button type="submit" name="redirect"></button>
                            </form>
                        </div>
                        {% endif %}
<!-- # CODE 4 -->
                </div>
            </section>
{% endblock %}

{% block jsfile %}
<script>
    link = document.getElementById('red-link');
    if (link != null) {
        setTimeout(function(){
            //document.getElementById("redirect").submit();
            window.location.href = link;
         }, 500);
    }
</script>
{% endblock %}

app/templates/app/surveys.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<style>

</style>
{% endblock %}
{% block content %}
            <section class="gridWrapper padGridWrapper">
                <div class="boxLeft pad">
                    <div class="boxHeader">
                        <h1>Add Survey</h1>
                    </div>
                    <div id="formAdd"class="boxForm">
                        <h1>Enter the Survey name:</h1>
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" name="formAdd">ADD</button>
                        </form>
                    </div>
                </div>
                <div class="boxRight pad">
                    <div class="boxHeader">
                        <h1>List</h1>
                    </div>
                    <div class="cardContainer" style="overflow-x:auto;">
                            <table id="creators-table" data-name="product-table">
                                <thead>
                                    <tr id="tableHeader">
                                        <th scope="col">Action!</th>
                                        <th scope="col">ID</th>
                                        <th scope="col">Language</th>
                                        <th scope="col">First:</th>
                                        <th scope="col">Zero:</th>
                                        <th scope="col">Last:</th>
                                        <th scope="col">Redirect To</th>
                                        <th scope="col">Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for survey in surveys %}
                                        {% if survey.survey_zero %}
                                        <tr class="tbc study-zero">
                                        {% elif survey.first_survey %}
                                        <tr class="tbc study-first">
                                        {% elif survey.last_survey %}
                                        <tr class="tbc study-last">
                                        {% else %}
                                        <tr class="tbc">
                                        {% endif %}
                                            <td class="button-table"><a href="{% url 'app:test-settings' testid=survey.id %}">Details</a></td>
                                            <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{survey.id}}</td>
                                            <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{survey.language}}</td>
                                            <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{survey.first_survey}}</td>
                                            <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{survey.survey_zero}}</td>
                                            <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{survey.last_survey}}</td>
                                            <td><img src="{% static 'app/type.png' %}" class="imgCell" height="24" width="24">{{survey.redirect_to}}</td>
                                            <td><img src="{% static 'app/name.svg' %}" class="imgCell" height="24" width="24">{{survey.name}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                    </div>
                </div>
            </section>
            {% if messages %}
            <div id="errorBar" class="error_message">
                {% for message in messages %}
                <span>{{ message }}</span> 
                {% endfor %}
                <button class="error_button" onclick="errorBar()"> X </button>
            </div>
            {% endif %}
{% endblock %}

{% block jsfile %}
{% endblock %}

app/templates/app/template-edit.html
{% extends "app/header.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<style>
</style>
{% endblock %}
{% block content %}
            <section class="gridWrapper padGridWrapper">
                <div class="boxLeft pad">
                    <div class="boxHeader">
                        <h1>Template Settings</h1>
                        <span type="button" id="delete" class="collapsible"><a href="{% url 'app:test-templatedelete' templateid=template.id %}" onclick="return confirm('Are you sure you want to delete this item?');"><img src="{% static 'app/close.svg' %}" height="24" width="24"></a></span>
                        <div class="boxInfoHome">
                            <a target="_blank" href="{% url 'app:preview-template' templateid=template.id %}">preview</a>
                        </div>
                    </div>
                </div>
                <div class="boxRight pad">
                    <div class="boxHeader">
                        <h1>Settings</h1>
                    </div>
                    <!-- section setting -->
                    <div class="boxHeader">
                        <div class="boxForm">
                            <form id="editTemplate" method="post">
                                {% csrf_token %}
                                {{ form_edit_template }}
                                <button type="submit" name="editTemplate">EDIT TEMPLATE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            {% if messages %}
            <div id="errorBar" class="error_message">
                {% for message in messages %}
                <span>{{ message }}</span> 
                {% endfor %}
                <button class="error_button" onclick="errorBar()"> X </button>
            </div>
            {% endif %}
{% endblock %}

{% block jsfile %}
{% endblock %}